spring.application.name=demo
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=debug

#spring.profiles.active=ollama

# --- OLLAMA PROFILE ---
#spring.config.activate.on-profile=ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.7

# --- THIRD-PARTY PROFILE ---
#spring.config.activate.on-profile=thirdparty

#openrouter:
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=openai/gpt-oss-20b:free

#local:
#spring.ai.openai.api-key=llama3.2
#spring.ai.openai.base-url=http://localhost:11434
#spring.ai.openai.chat.options.model=llama3.2

# --- OPENAI ---

openai.api.key=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
openai.base.url=https://openrouter.ai/api/v1
openai.model=openai/gpt-oss-20b:free