spring.application.name=demo
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=debug

#spring.profiles.active=ollama

# --- OLLAMA PROFILE ---
#spring.config.activate.on-profile=ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.7

# --- THIRD-PARTY PROFILE ---
#spring.config.activate.on-profile=thirdparty

#openrouter:
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=nvidia/nemotron-3-ultra-550b-a55b:free

spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

#local:
#spring.ai.openai.api-key=llama3.2
#spring.ai.openai.base-url=http://localhost:11434
#spring.ai.openai.chat.options.model=llama3.2

# --- OPENAI ---

openai.api.key=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
openai.base.url=https://openrouter.ai/api/v1
openai.model=nvidia/nemotron-3-ultra-550b-a55b:free

spring.datasource.url=jdbc:h2:file:~/chatmemory/chatmemory:AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=shreedhar
spring.datasource.password=12345
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=vector

audit.token-usage.enabled=true